repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: sbt
        args: ['fmtCheck', 'fixCheck']
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
