addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.7")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("au.com.onegeek"           %% "sbt-dotenv"          % "2.1.233")
addSbtPlugin("com.timushev.sbt"          % "sbt-rewarn"          % "0.1.3")
